name: Hourly Code Commit

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate random code
        run: |
          mkdir -p snippets
          echo "print('Hello $(date -u)')" > snippets/snippet_$(date -u +%Y%m%d_%H%M).py
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "feat: hourly update $(date -u)" || echo "No changes"
          git push
